# Generated by Django 4.1.2 on 2022-11-15 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type_property', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('type_attendance', models.CharField(max_length=50)),
                ('type_project', models.CharField(max_length=50)),
                ('with_one', models.CharField(max_length=50)),
                ('with_two', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
