# Generated by Django 4.1.2 on 2022-11-15 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_owner_scheduling_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
